[package]
name = "telserv"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "./src/server.rs"

[[bin]]
name = "client"
path = "./src/client.rs"

[dependencies]
crossterm = "0.28.1"
getrandom = "0.3.0"
rustls = "0.23.21"

